# -----------------------------------------------------------------------------
# layer.conf de meta-myapp
# Define cómo BitBake debe incluir esta capa (layer) en la build.
# -----------------------------------------------------------------------------

# Agrega los directorios 'conf' y 'classes' de esta capa al BBPATH
# (necesario para que BitBake encuentre las configuraciones y clases personalizadas)
BBPATH .= ":${LAYERDIR}"

# Indica dónde buscar recetas y bbappend dentro de esta capa.
# Busca en cualquier recipes-* y sus subcarpetas.
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

# -------------------------
# Identificación de la capa
# -------------------------

# Nombre lógico de la colección de recetas de esta capa
BBFILE_COLLECTIONS += "meta-myapp"

# Patrón de archivos de receta que pertenecen a esta capa
BBFILE_PATTERN_meta-myapp = "^${LAYERDIR}/"

# Prioridad de esta capa (número mayor = mayor prioridad si hay conflictos)
BBFILE_PRIORITY_meta-myapp = "6"

# -------------------------
# Dependencias de la capa
# -------------------------

# Esta capa depende al menos de la capa 'core' (meta)
LAYERDEPENDS_meta-myapp = "core"

# Series de Yocto con las que es compatible esta capa.
# 'walnascar' es la branch de Yocto que estamos usando.
LAYERSERIES_COMPAT_meta-myapp = "walnascar"
